[project]
name = "lfreader-server"
version = "0.0.0"
dependencies = [
  "aiohttp",
  "beautifulsoup4",
  "feedparser",
  "fastapi",
  "uvicorn[standard]",
]

[project.scripts]
lfreader-server = "lfreader_server.app:main"
lfreader-lookup = "lfreader_lookup.app:main"

